# 홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "" #질문 업로드 위해 비워둠
APP_SECRET: "" #질문 업로드 위해 비워둠

# 계좌번호 앞 8자리
CANO: "64******" #질문 업로드 위해 가려둠
# 계좌번호 뒤 2자리
ACNT_PRDT_CD: "08"

# 도메인
URL_BASE: "https://openapi.koreainvestment.com:9443"

# HTS ID
HTS_ID: "@04*****" #질문 업로드 위해 가려둠